### ISSUE TITLE
Investigate using the compiled template for the analysis

### ISSUE THREAD

**Issue by stof** [twigstan/twigstan#1]
Requiring node transformers for each type of node makes this analyzer incompatible with Twig extensions adding more nodes, unless a twigstan extension (which is something that does not exist) provides a custom node transformer.

The readme explains that the `.` operator of Twig is hard to analyze and that you transform it to a call to a `twigstan_get_property_or_call_method` function. But this is actually the way this `.` operator is compiled: it is turned into a call to `Twig\Extension\CoreExtension::getAttribute()` (except for some special optimizable cases, that get compiled to direct array access, which would be analyzable by PHPStan directly)

**Comment by ruudk** [comment]
> Requiring node transformers for each type of node makes this analyzer incompatible with Twig extensions adding more nodes, unless a twigstan extension (which is something that does not exist) provides a custom node transformer.

Yes, that's a drawback, but not unsolvable. 

Others ([1](https://github.com/deprecated-packages/twig-phpstan-compiler), [2](https://github.com/driveto/phpstan-twig)) have tried to use Twig's compiled source before. The downside of using those sources is that it contains lots of extra code that can produce errors when analyzing it. This leads to many false positives. 

For example:
```twig
{% if navigationTabActive == 'partners' %} class="active"{% endif %}
``` 
becomes:
```php
if (((isset($context["navigationTabActive"]) || array_key_exists("navigationTabActive", $context) ? $context["navigationTabActive"] : (function () { throw new RuntimeError('Variable "navigationTabActive" does not exist.', 39, $this->source); })()) == "partners")) {
            yield " class=\"active\"";
        }
```

When the `$context` would have been typed with `array{navigationTabActive: string}` it would produce something like "condition is always true, navigationTabActive always exists in $context". Same for the array_key_exists. 

By transforming every node manually, we can create clean and simple code that is easier to analyse:
```php
if ($navigationTabActive == 'partners'} {
    echo ' class="active"';
}
```

Another reason for doing the manual transforming was that I wanted to render the blocks wherever they are defined with the context at that line. Transforming these blocks in these places made it easier.  For example, how would you instruct PHPStan to analyse `block_submain` function with the current `$context` when it sees `yield from $this->unwrap()->yieldBlock('submain', $context, $blocks);`

Same for extending a template. The context at the end of the template, should be validated against the requirements for the template it tries to extend. Currently, the `twigstan_extends` method is written at the end of the PHP file. 

> The readme explains that the `.` operator of Twig is hard to analyze and that you transform it to a call to a `twigstan_get_property_or_call_method` function. But this is actually the way this `.` operator is compiled: it is turned into a call to `Twig\Extension\CoreExtension::getAttribute()` (except for some special optimizable cases, that get compiled to direct array access, which would be analyzable by PHPStan directly)

Since I am not using the compiled source, there was also no reason to call `CoreExtension::getAttribute` as the code will not be executed anyway. It only purpose was to instruct PHPStan what the type would be. I could have kept it similar as `CoreExtension::getAttribute` and then let PHPStan figure that out. But it would require more arguments to be passed. 

> Investigate using the compiled template for the analysis

This is still something we can try out. When I started with this, I saw more drawbacks than upside to using those artifacts. But maybe it will be easier with the knowledge I have at this point.

**Comment by stof** [comment]
Given that blocks can be rendered on their own and they create their own scope, I would think that they still need to be analyzed partially on their own. If we make a parallel from Twig templates to PHP classes, blocks would be the equivalent of protected methods.
However, I agree that tracking what their input is might get harder this way.

> When the `$context` would have been typed with `array{navigationTabActive: string}` it would produce something like "condition is always true, navigationTabActive always exists in $context". Same for the array_key_exists.

This case of accessing Twig variables in the context is a good point. However, maybe this could be achieved by using a Twig NodeVisitor replacing NameExpression nodes with a special node compiling variables to such PHP variables (only during twigstan analysis, not during normal Twig usage) and then running the normal Twig compiler (which would support all custom nodes).

**Comment by stof** [comment]
Note that this replacement of variables will also require replacing variable assignments. While this is easy to do for `{ % set %}` nodes (as we can also replace them in a similar way), it could be more tricky for the `loop` variable assigned by the LoopNode.
So maybe we should keep compiling things to use `$context` but only simplifying the compilation of variable usages (in NameExpression) by removing the checks for undefined variables in the compiled code (so that phpstan reports usages of undefined array keys). I think phpstan might be good enough at analyzing array shapes for this to work (and it might make it easier to analyze includes (which pass an array shape of context) or `Environment::render()` usages in PHP code (if the Twig analysis end up being integrated with the phpstan analysis of the PHP code)

**Comment by ruudk** [comment]
I'm currently working on a new prototype that takes the compiled PHP files from Twig and optimizes them further for analysis by PHPStan.

**Comment by ruudk** [comment]
I just pushed a big refactoring that let's go of the old Transforming concept. It now uses Twig's compiled sources. I updated the readme to reflect this.
