### ISSUE TITLE
Make level configurable

### ISSUE THREAD

**Issue by ruudk** [twigstan/twigstan#12]
Currently the level is set to 8 by default:
https://github.com/twigstan/twigstan/blob/7c8eb1cccfea6d5b56258b99f48dc6241bf39be4/src/Application/PHPStanRunner.php#L49

This should be configurable. 

Maybe we should not set the level at all, and let the end-user reference their own PHPStan configuration file.

**Comment by VincentLanglet** [comment]
> Maybe we should not set the level at all, and let the end-user reference their own PHPStan configuration file.

This could solve the following issues there is like:
- The level is not configurable
- Stricter option are not configurable (like checkImplicitMixed or checkBenevolentUnionTypes which are kinda a level 10)
- Some config option like parallel, phpVersion, caching, etc might be useful
- It should be able to enable `bleedingEdge`

But on the other side, not all PHPStan options should be available
- Lot of stricter option (enabled with strict-rules) would not make any sens in the generated php
- Phpstan symfony/doctrine/phpunit extensions are useless for twigstan
- Error formatter is useless since twigstan render differently
- Certainly more

This would certainly mean having 
- a phpstan.neon config
- a twigstan.neon config
- a phpstan-twigstan.neon config with the phpstan config used by twigstan

This doesn't seems great.

I would feel more natural having
```
parameters:
    phpstan:
        level: 8
        bleedingEdge: true
        checkImplicitMixed: false
        checkBenevolentUnionTypes: false
```
And adding support for some option, 1 by 1 when needed.

This would "just" need to generate a phpstan config which seems doable since it's already the case
https://github.com/twigstan/twigstan/blob/7c8eb1cccfea6d5b56258b99f48dc6241bf39be4/src/Application/PHPStanRunner.php#L42-L57

Using a ValueObject with all the PHPStan option supported might be useful for the future.
